<!DOCTYPE html>
<html>
    <head>
        <title>Mapa moci | IHNED.cz</title>
        <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
        <meta http-equiv="content-type" content="text/html; charset=win-1250" />
        <meta http-equiv="content-language" content="cs" />
        <meta http-equiv="expires" content="0" />
        <meta http-equiv="cache-control" content="no-cache" />
        <meta http-equiv="pragma" content="no-cache" />
        <meta name="description" content="" />
        <meta name="keywords" content="" />
        <meta name="author" content="all: Economia, a.s." />
        <meta name="copyright" content="&copy; 2013 Economia, a.s." />
        <meta name="googlebot" content="snippet" />
        <script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script>
        <link rel="stylesheet" type="text/css" href="http://ihned.cz/css/11/allwebs.css?ver=17" id="style-0" />
        <link rel="stylesheet" type="text/css" href="http://ihned.cz/css/11/000000.css?v55" id="style-1" />
        <link rel="stylesheet" type="text/css" href="http://ihned.cz/css/11/allwebs_hh.css" media="handheld" id="style-h" />
        <link rel="stylesheet" type="text/css" href="http://zpravy.ihned.cz/css/11/detail.css?ver=13" />
        <link rel="shortcut icon" href="http://ihned.cz/img/_allwebs/favicon.ico" />
        <link rel="alternate" type="application/rss+xml" title="rss.ihned.cz" href="http://ihned.cz/?p=000000_rss" />
        <link rel="alternate" media="handheld" href="http://m.ihned.cz/" />

        <meta property="fb:app_id" content="160152434038663" />
        <meta property="og:type" content="article" />
        <meta property="og:url" content="http://ihned.cz/mapamoci" />
        <meta property="og:title" content="Mapa moci" />
        <meta property="og:image" content="http://ihned.cz/img/mapamoci/fallback.png" />
        <meta property="og:description" content="Server IHNED.cz pøipravil pøehlednou mapu zmìn, které provedli ministøi nové vlády Jiøího Rusnoka za 14 dní od svého jmenování." />
        <link href="/css/mapamoci/screen.css" rel="stylesheet" type="text/css" />
    </head>
    <body bgcolor="white">
        <div id="ihned">
            <div id="head">
                <div id="logo"><h1><a href="http://ihned.cz/" title="www.ihned.cz"><span></span>www.ihned.cz</a></h1></div>
                <div id="search-box" style="background: white;">

                </div>
                <div id="menu1">

                </div>
            </div>

            <div id="main">
                <div class="backFromGallery" style="display: block;">
                    <div class="closebtn"></div>
                    <a href="http://ihned.cz/">Zavøít vizualizaci a vrátit se zpìt</a>
                </div>
                <h1>Mapa moci</h1>
                <p>Server IHNED.cz pøipravil pøehlednou mapu zmìn, které provedli ministøi nové vlády Jiøího Rusnoka za 14 dní od svého jmenování. Zahrnuje každou pozici od námìstkù po vedoucí jednotlivých odborù napøíè resorty, na tøech z nich ještì ministøi nikoho nevymìnili. Vizualizace zobrazuje údaje platné 23. èervence v 16 hodin. S dalšími obmìnami ji budeme prùbìžnì aktualizovat.</p>

                <div id="fallback" class="incapable">
                    <p>Váš prohlížeè je bohužel zastaralý a nepodporuje interaktivní vizualizace. Doporuèujeme jej aktualizovat, <a href="http://www.browserchoice.eu/">stáhnout jiný</a> nebo použít <a href="http://www.google.com/chromeframe">Google Chrome Frame</a>. Mezitím bude aplikace pracovat pouze v omezeném režimu.</p>
                    <img src="/img/mapamoci/fallback.png" alt="Vizualizace množství lidí, kteøí byli vymìnìni na jednotlivých ministerstvech" />
                </div>

                <div id='content' class="incapable">
                    <ul id="sortSelector" class="selector">
                        <li data-tooltip="Pod touto záložkou pøehlednì zjistíte, na kterém ministerstvu se vymìnilo nejvíce lidí. Èím vyšší je tmavý sloupec, tím více zmìn na postech námìstkù, øeditelù a vedoucích probìhlo. Kurzorem ve sloupcích najdete konkrétní jména." data-content="changed" class="active">Podle poètu výmìn</li>
                        <li data-tooltip="Graf ukazuje, v jak vysokých patrech svých úøadù už ministøi sáhli ke zmìnám. Èím výše jsou tmavá pole, tím jsou novì obsazené posty významnìjší – od námìstkù, pøes øeditele celých sekcí, po vedoucí jednotlivých odborù." data-content="importance">Podle významu pozic</li>
                        <li data-tooltip="Tento graf je seøazen podle jednotlivých sekcí ministerstev. Podle tmavých polí zjistíte, ve kterých sekcích a pod nì spadajících odborech se událo nejvíce zmìn." data-content="original">Podle odborù ministerstev</li>
                    </ul>
                    <dl id="legend">
                        <dt class="old">svìtle modrá</dt>
                        <dd class="old">Pùvodní pracovníci</dd>
                        <dt class="new">tmavì modrá</dt>
                        <dd class="new">Vymìnìní pracovníci</dd>
                    </dl>
                </div>
                <p>Zapomnìli jsme na nìjakého námìstka èi vedoucího odboru? <a href="https://docs.google.com/a/economia.cz/forms/d/1ZnDynmfyh__TZZqMMzT1jHwDdCt4cnaQdgO1IYTfeu8/viewform">Napište nám</a>, my údaje aktualizujeme.</p>
                <p id="autori"><em>Autoøi: Jakub Wittka, Lucie Kuèerová, Jan Koudela</em></p>
                <div class="social-bottom-detail">
                    <div class="fb-bottom"><div id="fb-root"></div><script src="http://connect.facebook.net/cs_CZ/all.js#appId=218617268163634&amp;xfbml=1"></script><fb:like href="http://ihned.cz/mapamoci" send="false" layout="box_count" width="90" show_faces="false" action="recommend" font="arial"></fb:like></div>
                    <div class="tw-bottom"><a href="http://twitter.com/share" class="twitter-share-button" data-count="vertical" data-via="iHNed_zpravy" data-url="http://ihned.cz/mapamoci">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
                    </div>
                    <div class="one-plus-bottom">
                        <g:plusone size="tall" href="http://ihned.cz/mapamoci"></g:plusone>
                    </div>

                    <div class="addthis_toolbox addthis_32x32_style addthis_default_style" addthis:url="http://ihned.cz/mapamoci">
                        <a class="addthis_button_print" title="Print"></a>
                        <a class="addthis_button_email" title="Poslat e-mailem"></a>
                        <a class="addthis_button_compact" title="Sdílet - další služby"></a>
                        <a class="addthis_counter addthis_bubble_style"></a>
                    </div>
                </div>
            </div>

            <div id="foot">
                <div class="header">
                    <div class="slash">|</div><a href="http://prihlaseni.ihned.cz/" class="join">Pøihlásit se do</a>
                    <div class="slash">|</div><a href="http://eol.ihned.cz/mobilni-zpravodajstvi/">SMS</a>
                    <div class="slash">|</div><a href="http://eol.ihned.cz/mobilni-zpravodajstvi/">MMS</a>
                    <div class="slash">|</div><a href="http://m.ihned.cz/">mobilní verze</a>
                    <div class="socials">
                        <a href="http://www.facebook.com/ihned.cz" class="ico-facebook"></a>
                        <a href="http://twitter.com/IHNED_zpravy" class="ico-twitter"></a>
                        <a href="http://rss.ihned.cz/" class="ico-rss"></a>
                        <!-- a href="http://linkedin.com" class="ico-linkedin"></a -->
                    </div>
                    <div id="search-box-ov">
                        <form action="index.php" method="get">
                            <input type="text" name="ov[full_text_key]" size="8" class="search-input-ov" value="Hledejte v OBCHODNÍM VÌSTNÍKU" onfocus="if(this.value=='Hledejte v OBCHODNÍM VÌSTNÍKU')this.value='';" onblur="if(this.value=='')this.value='Hledejte v OBCHODNÍM VÌSTNÍKU';" title="" />
                                <input type="image" value="Hledat" src="http://ihned.cz/img/11_0/search-submit.gif" alt="Hledat v OV" class="search-submit-ov" title="Hledat v OV" />
                            <input type="hidden" name="p" value="301000_fulltextresult">
                            <input type="hidden" name="ov[action]" value="fulltext_overview">
                            <input type="hidden" name="ov[fulltext_test]" value="fulltext">
                        </form>
                    </div>

                </div>
                <div class="content">
                    <div id="fc1" class="fc">
                        <div class="heading">IHNED+</div>
                        <a href="http://prihlaseni.ihned.cz/index.php?p=0R0000_registrace">Zaregistrujte se zdarma</a>
                        <a href="http://ihned.cz/ihned-plus/">Poøiïte si IHNED+</a>
                    </div>
                    <div id="fc2" class="fc">
                        <div class="heading">Více informací o</div>
                        <a href="http://eol.ihned.cz/kontakty-nova-media/" rel="nofollow">Redakce a kontakty</a>
                        <a href="http://eol.ihned.cz/online-inzerce/" rel="nofollow">Inzerce</a>
                        <a href="http://kas.economia.ihned.cz/cz/" rel="nofollow">Konferenèní servis</a>
                        <a href="http://www.benefitklub.cz/" rel="nofollow">Benefitklub</a>
                        <a href="http://predplatit.ihned.cz/?utm_source=vlastni+odkazy&utm_medium=paticka&utm_campaign=ihned_cz" rel="nofollow">Pøedplatné</a>
                        <div class="heading normal">Zákaznická linka: 800 11 00 22</div>
                        <a href="m&#97;ilto:&#114;&#101;&#100;&#97;&#107;&#99;&#101;&#64;&#105;&#104;&#110;&#101;&#100;&#46;&#99;&#122;">Napište nám</a>
                    </div>
                    <div id="fc3" class="fc">
                    <div class="heading"><a href="http://ihned.cz/" rel="nofollow">IHNED.cz</a></div>
                        <a href="http://ihned.cz" rel="nofollow">Úvodní stránka</a>
                        <a href="http://zpravy.ihned.cz/" rel="nofollow">HN Zprávy</a>
                        <a href="http://byznys.ihned.cz/" rel="nofollow">HN Byznys</a>
                        <a href="http://life.ihned.cz/" rel="nofollow">HN Life</a>
                        <a href="http://art.ihned.cz/" rel="nofollow">HN Art</a>
                        <a href="http://tech.ihned.cz/" rel="nofollow">HN Tech</a>
                        <a href="http://sport.ihned.cz/" rel="nofollow">HN Sport</a>
                        <a href="http://dialog.ihned.cz/" rel="nofollow">HN Dialog</a>
                        <a href="http://tech.ihned.cz/hnfuture/" rel="nofollow">HN Future</a>
                        <a href="http://multimedia.ihned.cz/fotogalerie/" rel="nofollow">Foto a video</a>

                    </div>
                    <div id="fc4" class="fc">
                    <div class="heading"><a href="http://economia.ihned.cz/" rel="nofollow">Economia, a. s.</a></div>
                        <a href="http://hn.ihned.cz/" rel="nofollow">Hospodáøské noviny a IHNED.cz</a>
                        <a href="http://ekonom.ihned.cz/" rel="nofollow">Ekonom</a>
                        <a href="http://respekt.ihned.cz/" rel="nofollow">Respekt</a>
                        <a href="http://mam.ihned.cz/" rel="nofollow">Marketing a Media</a>
                        <a href="http://bankovnictvi.ihned.cz/" rel="nofollow">Bankovnictví</a>
                        <a href="http://business-spotlight.ihned.cz/" rel="nofollow">Business Spotlight</a>
                        <a href="http://financnimanagement.ihned.cz/" rel="nofollow">Finanèní management</a>
                        <a href="http://fpweb.ihned.cz/" rel="nofollow">Finanèní poradce</a>
                        <a href="http://hrmanagement.ihned.cz/" rel="nofollow">HR Management</a>
                        <a href="http://logistika.ihned.cz/" rel="nofollow">Logistika</a>
                        <a href="http://managerweb.ihned.cz/" rel="nofollow">ManagerWeb</a>
                        <a href="http://moderniobec.ihned.cz/" rel="nofollow">Moderní obec</a>
                        <a href="http://modernirizeni.ihned.cz/" rel="nofollow">Moderní øízení</a>
                        <a href="http://ov.ihned.cz/" rel="nofollow">Obchodní vìstník</a>
                        <a href="http://odpady.ihned.cz/" rel="nofollow">Odpady</a>
                        <a href="http://pravniradce.ihned.cz/" rel="nofollow">Právní rádce</a>
                        <a href="http://stavitel.ihned.cz/" rel="nofollow">Stavitel</a>
                        <a href="http://technik.ihned.cz/" rel="nofollow">Technik</a>
                        <a href="http://probyznys.info/" rel="nofollow">ProByznys.info</a>
                    </div>
                    <div id="fc5" class="fc">
                        <div class="hn pngfix"></div>
                        <div class="ihn pngfix"></div>
                        <div class="text">
                            <a href="http://eol.ihned.cz/copyright" rel="nofollow">Copyright</a> &copy; 1996-2013 Economia,  a.s., Hospodáøské noviny IHNED ISSN 1213 - 7693 <br />
                            <a href="http://eol.ihned.cz/online-inzerce/" rel="nofollow">Informace o inzerci</a>, inzertní kontakt <a href="m&#97;ilto:&#105;&#110;&#122;&#101;&#114;&#99;&#101;&#64;&#105;&#104;&#110;&#101;&#100;&#46;&#99;&#122;">&#105;&#110;&#122;&#101;&#114;&#99;&#101;&#64;&#105;&#104;&#110;&#101;&#100;&#46;&#99;&#122;</a>, redakèní kontakt <a href="m&#97;ilto:&#114;&#101;&#100;&#97;&#107;&#99;&#101;&#64;&#105;&#104;&#110;&#101;&#100;&#46;&#99;&#122;">&#114;&#101;&#100;&#97;&#107;&#99;&#101;&#64;&#105;&#104;&#110;&#101;&#100;&#46;&#99;&#122;</a>. Další kontakty <a href="http://eol.ihned.cz/kontakty-nova-media/">zde</a>.
                        </div>
                    </div>
                </div>
            </div>
            <div class="clean"></div>
        </div>
        <script type="text/javascript">
          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-41281738-1']);
          _gaq.push(['_trackPageview']);

          (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();

        </script>
        <script src="http://service.ihned.cz/js/jquery.min.js"></script>
        <script src="http://service.ihned.cz/js/d3.v3.min.js"></script>
        <script src="http://service.ihned.cz/js/modernizr.svg.min.js"></script>
        <script src="http://service.ihned.cz/js/jquery.scrollTo.js"></script>
        <script src="/js/mapamoci/Tooltip.js" type="text/javascript"></script>
        <script src="/js/mapamoci/base.js" type="text/javascript"></script>
        <script src="http://service.ihned.cz/spreadsheet/bigfilter.php?key=0AtY6fMYiLLJNdEVIOHQtNEdFNTlFdGZMYzFNY3pVbmc&amp;numsheets=14&amp;nocols=1&amp;cb=init&amp;forcecache=1"></script>
        <!-- (C)2000-2013 Gemius SA - gemiusAudience / ihned.cz / Politika-ostatni -->
        <script type="text/javascript">
        <!--//--><![CDATA[//><!--
        var pp_gemius_identifier = new String('nGs1L4fAgPE8BNmS95OaoLdenFmwIDAHq2BMaKrRiRP.E7');
        //--><!]]>
        </script>
        <script type="text/javascript" src="http://ihned.cz/js/xgemius.js"></script>
         <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#username=ihned"></script>

    </body>
</html>
